In [4]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
splits = {'train': 'train.tsv', 'validation': 'dev.tsv'}
df_train = pd.read_csv("hf://datasets/s-nlp/ru_paradetox/" + splits["train"], sep="\t")
df_val = pd.read_csv("hf://datasets/s-nlp/ru_paradetox/" + splits["validation"], sep="\t")

In [5]:
df_train.head()

,ru_toxic_comment,ru_neutral_comment
0,"и,чё,блядь где этот херой был до этого со свои...","Ну и где этот герой был,со своими доказательст..."
1,"и,чё,блядь где этот херой был до этого со свои...",Где этот герой был до этого со своими доказате...
2,"и,чё,блядь где этот херой был до этого со свои...","и,где этот герой был до этого со своими доказа..."
3,"О, а есть деанон этого петуха?","О, а есть деанон"
4,"херну всякую пишут,из-за этого лайка.долбоебизм.","Чушь всякую пишут, из- за этого лайка."

In [6]:
df_val.head()

,ru_toxic_comment,ru_neutral_comment
0,пиздеж! температуры горения хватит чтобы её ра...,Враньё! Температуры горения хватит чтобы ее ра...
1,пиздеж! температуры горения хватит чтобы её ра...,"неправда,температуры горения хватит чтобы расп..."
2,пиздеж! температуры горения хватит чтобы её ра...,Враньё! Температуры горения хватит на чтобы её...
3,а ты чмо там был.ты вообще служил.гандон,А ты там был? Ты вообще служил?
4,пиздабол ---- а сам где кормишься ?,а сам где кормишься ?

In [7]:
df_train.describe()

,ru_toxic_comment,ru_neutral_comment
count,11090,11090
unique,6948,10873
top,"и,чё,блядь где этот херой был до этого со свои...",Я там через день бываю
freq,3,3

In [8]:
df_val.describe()

,ru_toxic_comment,ru_neutral_comment
count,1116,1116
unique,800,1087
top,пиздеж! температуры горения хватит чтобы её ра...,как его вообще со стадиона выпустили
freq,3,2

In [9]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11090 entries, 0 to 11089
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ru_toxic_comment    11090 non-null  object
 1   ru_neutral_comment  11090 non-null  object
dtypes: object(2)
memory usage: 173.4+ KB

In [10]:
df_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ru_toxic_comment    1116 non-null   object
 1   ru_neutral_comment  1116 non-null   object
dtypes: object(2)
memory usage: 17.6+ KB