In [6]:
import pandas as pd

In [8]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("textdetox/multilingual_toxic_spans", split="ru")

In [9]:
df = pd.DataFrame(ds)

In [10]:
df.head()

,Sentence,Negative Connotations
0,во дебил ты пан-баран))))))))))))))))))). евре...,"дебил, пан-баран, еврейское тв, даун"
1,завтра в хабаровске вдвшники будут разгонять б...,быдло
2,"эта походу старое фото,в середине хряк телепуз...","хряк, телепузик, редкая скотина"
3,а что рядом других что мужиков рядом не оказал...,"ублюдку, табло, перевелись"
4,"хули вы бляди клянчите классы ,просто помните.","хули,бляди"

In [11]:
df.describe()

,Sentence,Negative Connotations
count,999,999
unique,999,836
top,во дебил ты пан-баран))))))))))))))))))). евре...,сука
freq,1,10

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sentence               999 non-null    object
 1   Negative Connotations  999 non-null    object
dtypes: object(2)
memory usage: 15.7+ KB