In [1]:
import pandas as pd

In [3]:
from pathlib import Path
from kaggle.api.kaggle_api_extended import KaggleApi

data_dir = Path("../data")
data_dir.mkdir(parents=True, exist_ok=True)

api = KaggleApi()
api.authenticate()
api.dataset_download_files("alexandersemiletov/toxic-russian-comments", path=str(data_dir), unzip=True)

Dataset URL: https://www.kaggle.com/datasets/alexandersemiletov/toxic-russian-comments

In [5]:
data_list = []
with open("../data/dataset.txt", encoding="utf-8") as file:
    for line in file:
        labels = line.split()[0]
        text = line[len(labels) + 1:].strip()
        labels = labels.split(",")
        mask = [
            1 if "__label__NORMAL" in labels else 0,
            1 if "__label__INSULT" in labels else 0,
            1 if "__label__THREAT" in labels else 0,
            1 if "__label__OBSCENITY" in labels else 0,
        ]
        data_list.append((text, *mask))

In [6]:
df = pd.DataFrame(data_list, columns=["text", "normal", "insult", "threat", "obscenity"])

In [7]:
df.head()

,text,normal,insult,threat,obscenity
0,скотина! что сказать,0,1,0,0
1,я сегодня проезжала по рабочей и между домами ...,1,0,0,0
2,очередной лохотрон. зачем придумывать очередно...,1,0,0,0
3,"ретро дежавю ... сложно понять чужое сердце , ...",1,0,0,0
4,а когда мы статус агрогородка получили?,1,0,0,0

In [8]:
df.describe()

              normal         insult         threat      obscenity
count  248290.000000  248290.000000  248290.000000  248290.000000
mean        0.820351       0.148318       0.048439       0.017161
std         0.383895       0.355416       0.214693       0.129873
min         0.000000       0.000000       0.000000       0.000000
25%         1.000000       0.000000       0.000000       0.000000
50%         1.000000       0.000000       0.000000       0.000000
75%         1.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248290 entries, 0 to 248289
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   text       248290 non-null  object
 1   normal     248290 non-null  int64
 2   insult     248290 non-null  int64
 3   threat     248290 non-null  int64
 4   obscenity  248290 non-null  int64
dtypes: int64(4), object(1)
memory usage: 9.5+ MB